import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import Footer from "@/components/footer/footer";
import { ThemeContextProvider } from "@/context/themeContext";
import ThemeProvider from "@/providers/themeProvider";
import AuthProvider from "@/providers/authProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[100vw] overflow-x-hidden relative">
        <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
              <div className="min-h-[100vh] bg-primBg text-primText">
                <div className="lg:px-20 max-[1536px]:max-w-7xl max-[1280px]:max-w-5xl max-[1024px]:max-w-3xl sm:px-10 mx-auto px-1">
                  <Navbar />

                  {children}
                  <Footer />
                </div>
              </div>
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
